/**
 * Circuit Protocol — Machine-Readable Tool Capability Registry
 *
 * Defines all 30+ typed capabilities available to Circuit Agent,
 * their risk levels, authority requirements, and concurrency rules.
 *
 * Parallelization Rule:
 * Independent read-only tools run concurrently.
 * Mutation tools (borrow, withdraw, repay, etc.) are strictly serialized.
 */

export type ToolRiskLevel = "NONE" | "LOW" | "MEDIUM" | "HIGH";
export type ToolCostClass = "READ_ONLY" | "LOW_COMPUTE" | "HEAVY_ANALYSIS" | "ON_CHAIN_MUTATION";

export interface AgentToolCapability {
  name: string;
  category: "OBSERVATION" | "PLANNING" | "EXECUTION" | "AUTOMATION";
  description: string;
  risk_level: ToolRiskLevel;
  required_permission: boolean;
  required_authority: boolean;
  credit_cost_class: ToolCostClass;
  read_only: boolean;
  supports_background: boolean;
  supports_autonomous: boolean;
  max_arguments: number;
}

export const CAPABILITY_REGISTRY: Record<string, AgentToolCapability> = {
  // ── 1. Observation Tools (Read-Only, Fully Parallelizable) ──
  get_market: {
    name: "get_market",
    category: "OBSERVATION",
    description: "Fetch live price, 24h change, and volume for a tokenized equity market",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  get_market_history: {
    name: "get_market_history",
    category: "OBSERVATION",
    description: "Retrieve historical candles and volatility metrics for asset",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: false,
    supports_autonomous: true,
    max_arguments: 3,
  },
  get_oracle: {
    name: "get_oracle",
    category: "OBSERVATION",
    description: "Query real-time Pyth Hermes price feed and confidence interval",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  get_oracle_freshness: {
    name: "get_oracle_freshness",
    category: "OBSERVATION",
    description: "Inspect slot latency and staleness boundaries for price feeds",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_position: {
    name: "get_position",
    category: "OBSERVATION",
    description: "Read on-chain collateral and debt state for a specific equity mint",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  get_portfolio: {
    name: "get_portfolio",
    category: "OBSERVATION",
    description: "Synthesize full portfolio solvency, total collateral, total debt, and health factor",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_collateral: {
    name: "get_collateral",
    category: "OBSERVATION",
    description: "Read total collateral deposited across all equity vaults",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_debt: {
    name: "get_debt",
    category: "OBSERVATION",
    description: "Read current outstanding USDC debt and accrued interest",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_ltv: {
    name: "get_ltv",
    category: "OBSERVATION",
    description: "Calculate current aggregate Loan-to-Value in basis points",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_borrow_capacity: {
    name: "get_borrow_capacity",
    category: "OBSERVATION",
    description: "Calculate maximum allowable new debt before exceeding liquidation threshold",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  get_risk_state: {
    name: "get_risk_state",
    category: "OBSERVATION",
    description: "Query current monotonic Risk Ratchet state (SAFE, RESTRICTED, DEFENSIVE, EMERGENCY)",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 0,
  },
  get_permission: {
    name: "get_permission",
    category: "OBSERVATION",
    description: "Evaluate Circuit Permission Engine determination for an action and amount",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 4,
  },
  get_agent_authority: {
    name: "get_agent_authority",
    category: "OBSERVATION",
    description: "Read on-chain Agent Authority PDA limits, expiry, and revoked status",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  get_agent_tasks: {
    name: "get_agent_tasks",
    category: "OBSERVATION",
    description: "List all persistent background watchers, schedules, and automation tasks",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_transaction: {
    name: "get_transaction",
    category: "OBSERVATION",
    description: "Fetch confirmed Solana Devnet transaction details and log events",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: false,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_activity: {
    name: "get_activity",
    category: "OBSERVATION",
    description: "Read recent portfolio activity log and detected operational patterns",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_dbc_state: {
    name: "get_dbc_state",
    category: "OBSERVATION",
    description: "Read Meteora Dynamic Bonding Curve pool reserves, lifecycle stage, and quote threshold",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  get_dbc_pool: {
    name: "get_dbc_pool",
    category: "OBSERVATION",
    description: "Query verified Meteora DBC pool address for token pair",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  get_policy: {
    name: "get_policy",
    category: "OBSERVATION",
    description: "Inspect canonical Capital Policy parameters for current risk ratchet regime",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  get_decision_log: {
    name: "get_decision_log",
    category: "OBSERVATION",
    description: "Query immutable audit trail of past agent evaluations and confirmed actions",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },

  // ── 2. Planning Tools ──
  create_strategy: {
    name: "create_strategy",
    category: "PLANNING",
    description: "Synthesize a multi-step capital strategy plan bounded by risk thresholds",
    risk_level: "LOW",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "HEAVY_ANALYSIS",
    read_only: true,
    supports_background: false,
    supports_autonomous: true,
    max_arguments: 4,
  },
  validate_strategy: {
    name: "validate_strategy",
    category: "PLANNING",
    description: "Dry-run check whether proposed strategy steps satisfy Circuit Capital Policy",
    risk_level: "LOW",
    required_permission: true,
    required_authority: false,
    credit_cost_class: "LOW_COMPUTE",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  estimate_execution: {
    name: "estimate_execution",
    category: "PLANNING",
    description: "Simulate projected health factor, LTV, and slippage for action plan",
    risk_level: "LOW",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "LOW_COMPUTE",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 3,
  },
  estimate_credit_cost: {
    name: "estimate_credit_cost",
    category: "PLANNING",
    description: "Preview compute credit requirement before invoking Pro or background workflow",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: true,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 3,
  },

  // ── 3. Execution Tools (Strictly Serialized & Permission-Gated) ──
  request_deposit: {
    name: "request_deposit",
    category: "EXECUTION",
    description: "Deposit equity collateral into Circuit vault (Capital Recovery - Unconditionally Allowed)",
    risk_level: "LOW",
    required_permission: true,
    required_authority: false,
    credit_cost_class: "ON_CHAIN_MUTATION",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 3,
  },
  request_borrow: {
    name: "request_borrow",
    category: "EXECUTION",
    description: "Borrow USDC against equity collateral (Risk-Increasing - Requires SAFE/RESTRICTED and Authority)",
    risk_level: "HIGH",
    required_permission: true,
    required_authority: true,
    credit_cost_class: "ON_CHAIN_MUTATION",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 3,
  },
  request_repay: {
    name: "request_repay",
    category: "EXECUTION",
    description: "Repay outstanding USDC debt (Capital Recovery - Sacred and Always Permitted)",
    risk_level: "LOW",
    required_permission: true,
    required_authority: false,
    credit_cost_class: "ON_CHAIN_MUTATION",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 3,
  },
  request_withdraw: {
    name: "request_withdraw",
    category: "EXECUTION",
    description: "Withdraw equity collateral (Risk-Increasing - Blocked if debt exists in DEFENSIVE/EMERGENCY)",
    risk_level: "HIGH",
    required_permission: true,
    required_authority: true,
    credit_cost_class: "ON_CHAIN_MUTATION",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 3,
  },
  request_rebalance: {
    name: "request_rebalance",
    category: "EXECUTION",
    description: "Rebalance collateral allocations across multiple equities",
    risk_level: "HIGH",
    required_permission: true,
    required_authority: true,
    credit_cost_class: "ON_CHAIN_MUTATION",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 4,
  },
  request_recovery: {
    name: "request_recovery",
    category: "EXECUTION",
    description: "Execute mathematical minimum debt repayment d* to restore HF >= 1.05",
    risk_level: "LOW",
    required_permission: true,
    required_authority: false,
    credit_cost_class: "ON_CHAIN_MUTATION",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 2,
  },
  request_dbc_action: {
    name: "request_dbc_action",
    category: "EXECUTION",
    description: "Execute swap, enter, or exit liquidity on verified Meteora DBC pool",
    risk_level: "HIGH",
    required_permission: true,
    required_authority: true,
    credit_cost_class: "ON_CHAIN_MUTATION",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 4,
  },

  // ── 4. Automation Tools ──
  create_watch: {
    name: "create_watch",
    category: "AUTOMATION",
    description: "Create a persistent background condition watcher (survives browser close)",
    risk_level: "LOW",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "LOW_COMPUTE",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 4,
  },
  create_schedule: {
    name: "create_schedule",
    category: "AUTOMATION",
    description: "Create a scheduled periodic review task executed via durable server cron",
    risk_level: "LOW",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "LOW_COMPUTE",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 3,
  },
  create_auto_manage: {
    name: "create_auto_manage",
    category: "AUTOMATION",
    description: "Create an autonomous policy task for bounded health factor maintenance",
    risk_level: "MEDIUM",
    required_permission: true,
    required_authority: true,
    credit_cost_class: "HEAVY_ANALYSIS",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 4,
  },
  pause_task: {
    name: "pause_task",
    category: "AUTOMATION",
    description: "Pause an active background task",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  resume_task: {
    name: "resume_task",
    category: "AUTOMATION",
    description: "Resume a paused background task",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
  cancel_task: {
    name: "cancel_task",
    category: "AUTOMATION",
    description: "Permanently terminate a background task",
    risk_level: "NONE",
    required_permission: false,
    required_authority: false,
    credit_cost_class: "READ_ONLY",
    read_only: false,
    supports_background: true,
    supports_autonomous: true,
    max_arguments: 1,
  },
};

/**
 * Validates whether an array of tool names can safely execute concurrently.
 * Strictly requires all tools to be read_only: true.
 */
export function canRunInParallel(toolNames: string[]): boolean {
  if (!Array.isArray(toolNames) || toolNames.length <= 1) return true;
  return toolNames.every(name => {
    const cap = CAPABILITY_REGISTRY[name];
    return cap ? cap.read_only : false;
  });
}

/**
 * Returns tool capability metadata.
 */
export function getToolCapability(name: string): AgentToolCapability | undefined {
  return CAPABILITY_REGISTRY[name];
}

/**
 * Filter tools by whether the wallet has an active on-chain authority PDA.
 */
export function filterAvailableTools(hasActiveAuthority: boolean): AgentToolCapability[] {
  return Object.values(CAPABILITY_REGISTRY).filter(cap => {
    if (!hasActiveAuthority && cap.required_authority) return false;
    return true;
  });
}
