[package]
name = "circuit-risk-sdk"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Official CPI SDK for Circuit Risk Kernel and Risk Envelope on Solana"
license = "Apache-2.0"

[lib]
crate-type = ["lib"]
name = "circuit_risk_sdk"

[dependencies]
anchor-lang = { version = "1.2.0" }
thiserror = "2.0"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]
